paths:
  /api/products:
    get:
      summary: Obtiene todos los productos
      tags: [Products]
      responses: 
        "200": 
          description: Los productos fueron obtenidos satisfactoriamente
          content:
            application/json:
              schema: 
                type: array
                items: 
                  $ref: "#components/schemas/Product"
        "500":
          description: Error en el servidor
    post:
      summary: Crea un producto si se tiene el rol de admin o premium
      tags: [Products]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#components/requestBodies/newProduct"
      responses: 
        "200":
          description: "Se pudo crear el producto correctamente"
        "401":
          description: "No se pudo crear el producto correctamente ya que el usuario no cuenta con el rol requerido"

  
  /api/products/{pid}:
    get:
      summary: Obtiene un sólo producto de los disponibles, buscándolo por id
      tags: [Products]
      parameters:
      - name: pid
        in: path
        required: true
        description: id del producto que se desea solicitar
        schema:
          type: string
          example: 507f1f77bcf86cd799439011
      responses:
        "200":
          description: Producto obtenido de forma satisfactoria de la base de datos
          content:
            application/json:
              schema:
                $ref: '#components/schemas/Product'
        "404":
          description: "Producto no encontrado"
    put:
      summary: "Actualiza los datos de un producto si se tiene el rol de admin o el usuario es el dueño del mismo"
      tags: [Products]
        parameters:
        - name: pid 
          in: path
          required: true
          description: id del producto solicitado
          schema:
            type: string
        requestBody:
          content:
            application/json:
              schema:
                $ref: '#components/requestBodies/updateProduct'
        responses:
          "200":
            description: Producto actualizado de forma satisfactoria en la base de datos
    delete:
      summary: 'Borra un producto si se tiene el rol de admin o el usuario es el dueño del mismo'
      tags: [Products]
      parameters:
      - name: pid 
        in: path
        required: true
        description: id del producto solicitado
        schema:
          type: string
      responses:
        "200":
          description: Se borró de forma exitosa el producto
        "404":
          description: El producto no se pudo encotrar
        "401":
          descripcion: El producto no se pudo borrar ya que el usuario no es el dueño ni cuenta con el rol necesario

  /api/products/mockingproducts: 
    get:
      summary: "Muestra productos creados para visualizacion"
      tags: [Products]
      responses:
        "200":
          description: "Productos falsos mostrados"

components: 
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: ObjectId
          description: id autogenerado por mongo
        title:
          type: string
          description: Nombre del producto
        description:
          type: string
          description: Descripcion del producto
        price:
          type: number
          description: Precio del producto
        thumbnail:
          type: string
          description: URL de imagen del producto
        stock:
          type: number
          description: Stock disponible del producto
        code:
          type: number
          description: Codigo del producto
        category:
          type: string
          description: Categoria del producto
        owner:
          type: string
          description: Dueño del producto
      example:
        _id: 65e7c7689c16d54895f5082f
        title: "Pineapple" 
        description: "A tropical fruit" 
        price: 3.49 
        thumbnail: "N/A"
        stock: 20 
        code: "123450"
        category: "Fruits"
        owner: "pepe12@gmail.com"
  requestBodies:
    newProduct:
      type: object
      properties:
        _id:
          type: ObjectId
          description: id autogenerado por mongo
        title:
          type: string
          description: Nombre del producto
        description:
          type: string
          description: Descripcion del producto
        price:
          type: number
          description: Precio del producto
        thumbnail:
          type: string
          description: URL de imagen del producto
        stock:
          type: number
          description: Stock disponible del producto
        code:
          type: number
          description: Codigo del producto
        category:
          type: string
          description: Categoria del producto
        owner:
          type: string
          description: Dueño del producto
      example:
        _id: 65e7c7689c16d54895f5082f
        title: "Pineapple" 
        description: "A tropical fruit" 
        price: 3.49 
        thumbnail: "N/A"
        stock: 20 
        code: "123450"
        category: "Fruits"
        owner: "pepe12@gmail.com"
    updateProduct: 
      type: object
      properties:
      title:
          type: string
          description: Nombre del producto
        description:
          type: string
          description: Descripcion del producto
        price:
          type: number
          description: Precio del producto
        thumbnail:
          type: string
          description: URL de imagen del producto
        stock:
          type: number
          description: Stock disponible del producto
        code:
          type: number
          description: Codigo del producto
        category:
          type: string
          description: Categoria del producto
        owner:
          type: string
          description: Dueño del producto
      example:
        title: "Strawberries" 
        description: "A sweet fruit"
        price: 2.49 
        thumbnail: "N/A"
        stock: 30 
        code: "678901"
        category: "Fruits"

